### ISSUE TITLE
There is a space between Health and resources.

### ISSUE THREAD

**Issue by yangcunsam** [dlecina/ElvUI_NoBorders#1]
![image](https://user-images.githubusercontent.com/74395295/99189019-5ccc2500-27a2-11eb-803a-12defd13b9a9.png)

It doesn't look good because the background is permeated.

**Comment by yangcunsam** [comment]
![123](https://user-images.githubusercontent.com/74395295/99189066-acaaec00-27a2-11eb-99cc-9039ec470849.gif)

**Comment by dlecina** [comment]
This is due to a limitation with the solution. The border is not really removed, it's just invisible. If a better solution becomes available it will be used.
